### ISSUE TITLE
Zombies salen del mapa

### ISSUE THREAD

**Issue by javics2002** [Proyectos1-FDI-UCM/c2021-Grupo08#2]
### **Descripción**
Algunos zombies atraviesan el muro y salen del mapa, concretamente el zombie de la zona rosa en el nivel 1, tras dar una vuelta y el zombie de la zona roja en el nivel 2, nada mas empezar.
### **Pasos**
1. Observar al zombie de la zona rosa en el nivel 1 hasta que vaya hacia arriba y no pare
2. Observar al zombie de la zona roja en el nivel 2 nada mas empezar
### **Capturas de pantalla**
![image](https://user-images.githubusercontent.com/49459590/119273924-79dc2780-bc0d-11eb-97ab-ee159cde30cf.png)
![image](https://user-images.githubusercontent.com/49459590/119273925-7cd71800-bc0d-11eb-9d80-e589b4473507.png)

**Comment by josemiguelvdz** [comment]
También ocurre con el enemigo 1 del nivel 2 de la parte del puzle naranja.

https://user-images.githubusercontent.com/75903737/119492505-722c9800-bd5f-11eb-8c59-889c7524ef70.mp4

https://user-images.githubusercontent.com/75903737/119492516-75c01f00-bd5f-11eb-9cbc-832a29ed8a39.mp4
