### ISSUE TITLE
Ataque confuso

### ISSUE THREAD

**Issue by javics2002** [Proyectos1-FDI-UCM/c2021-Grupo08#3]
No se ha especificado el funcionamiento del ataque. Al usar una pistola he pensado que podía atacar a distancia y en todas las direcciones, pero solo hace daño a cuerpo a cuerpo, obligándote además a perder vida para matar un enemigo. ¿Es esto correcto?

**Comment by ssimoanto** [comment]
En el srpite del player aparecía una pistola, porque era un placeholder, no habiamos creado todaví el sprite final, que tiene un martillo. Gracias por la observación
